databases:
  - name: botany
    plan: starter
    region: ohio
services:
  - type: web
    plan: starter
    numInstances: 1
    name: botany
    env: python
    region: ohio
    buildCommand: "./bin/build.sh"
    startCommand: 'gunicorn --access-logformat ''%(h)s %(l)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" reqtime: %(M)s ms'' botany.wsgi:application'
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.7
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: botany
          property: connectionString
      - key: ALLOWED_HOSTS
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: botany.settings.prod
